

name: springboot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: actions/checkout@v2
    - name: build image 
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/githubspring2.2
    - name: docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/githubspring2.2
